spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ---your client id---
            client-secret: ---your client secret---
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://{your-tanent-here}.us.auth0.com/